# Generated by Django 2.2 on 2022-02-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsbrand',
            options={'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
    ]
